'use client'
import { NextAuthProvider } from '@/lib/providers'
import { Inter } from 'next/font/google'
import ResponsiveNavbar from '@/components/ResponsiveNavbar';
import { CartProvider } from 'react-use-cart'
import "bootstrap/dist/css/bootstrap.min.css";
//import './globals.css'
//import type { Metadata } from 'next'

const inter = Inter({ subsets: ['latin'] })
/*
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}*/

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang={'pt-BR'}>
      <head>
        <title>Title</title>
        <meta name='E-Store' content='E-Store' />
      </head>
      <body className={inter.className}>
        <NextAuthProvider>
          <CartProvider>
            <ResponsiveNavbar/>
            {children}
          </CartProvider>
        </NextAuthProvider>
      </body>
    </html>
  )
}
